### ISSUE TITLE
Is this lib a duplicate of STD?

### ISSUE THREAD

**Issue by lsagetlethias** [KSXGitHub/simple-js-yaml-port-for-deno#2]
Hello,

Did you see that: https://deno.land/std/encoding/#yaml

The standard library is already a port of JS-YAML library ; is there any difference between yours and the std one?

**Comment by KSXGitHub** [comment]
I wasn't aware of that. Thanks for letting me know.

**Comment by KSXGitHub** [comment]
And for your question. There is no difference save perhaps maintenance. I will frequently update js-yaml to latest version.
